apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 80
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: ingress_http
                    route_config:
                      virtual_config:
                        virtual_hosts:
                          - name: url-shortener
                            domains: ["*"]
                            routes:
                              - match:
                                  prefix: "/"
                                route:
                                  cluster: url-shortener
                    http_filters:
                      - name: envoy.filters.http.router
    clusters:
      - name: url-shortener
        connect_timeout: 0.25s
        type: STRICT_DNS
        load_assignment:
          cluster_name: url-shortener
          endpoints:
            - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: url-shortener.default.svc.cluster.local
                        port_value: 8080
