apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/akos011221/url-shortener.git"
    targetRevision: main
    path: kubernetes/envoy
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
